#!/bin/sh

BUILDROOT_VERSION=2023.02.8  # or another recent LTS version

set -xe

if [ -d ~/buildroot ]; then
	rm -rf ~/buildroot
else
	sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
	locale-gen
fi

cd ~

BUILDROOT_NAME=buildroot-$BUILDROOT_VERSION
wget https://buildroot.org/downloads/$BUILDROOT_NAME.tar.gz
tar -xf ./$BUILDROOT_NAME.tar.gz
rm -f ./$BUILDROOT_NAME.tar.gz
mv ./$BUILDROOT_NAME ./buildroot

# patches for buildroot packages
cd ~/patches
for FILE in $(find . -type f -name "*.patch" 2>/dev/null); do
	cp $FILE ~/buildroot/$FILE
done

cd ~/buildroot
if patch -p1 --dry-run < ~/sdl2-update-to-2.0.12.patch >/dev/null 2>&1; then
    patch -p1 < ~/sdl2-update-to-2.0.12.patch
else
    echo "Skipping SDL2 patch - doesn't apply to this buildroot version"
fi

if patch -p1 --dry-run < ~/toolchain-expose-BR2_TOOLCHAIN_EXTRA_EXTERNAL_LIBS-for-all-toolchain-types-2017.11.1.diff >/dev/null 2>&1; then
    patch -p1 < ~/toolchain-expose-BR2_TOOLCHAIN_EXTRA_EXTERNAL_LIBS-for-all-toolchain-types-2017.11.1.diff
else
    echo "Skipping toolchain patch - doesn't apply to this buildroot version"
fi
cp ~/rg35xxplus-buildroot-$BUILDROOT_VERSION.config ./.config
if [ -f ~/rg35xxplus-toolchain.tar.xz ]; then
 	tar -xf ~/rg35xxplus-toolchain.tar.xz -C /opt
else
	export FORCE_UNSAFE_CONFIGURE=1
	# Start with a completely fresh config to avoid legacy options
	make defconfig
	# Now apply our custom configuration for RG35XX Plus
	cat > ./.config << 'EOF'
BR2_arm=y
BR2_cortex_a9=y
BR2_ARM_ENABLE_NEON=y
BR2_ARM_ENABLE_VFP=y
BR2_ARM_EABIHF=y
BR2_ARM_FPU_NEON=y
BR2_ARM_INSTRUCTIONS_THUMB2=y
BR2_TOOLCHAIN_BUILDROOT=y
BR2_TOOLCHAIN_BUILDROOT_GLIBC=y
BR2_TOOLCHAIN_BUILDROOT_CXX=y
BR2_GCC_ENABLE_LTO=y
BR2_GCC_ENABLE_OPENMP=y

# Audio/Video packages and codecs for complete libav support
BR2_PACKAGE_FFMPEG=y
BR2_PACKAGE_FFMPEG_FFPLAY=y
BR2_PACKAGE_FFMPEG_FFPROBE=y
BR2_PACKAGE_FFMPEG_AVRESAMPLE=y
BR2_PACKAGE_FFMPEG_POSTPROC=y
BR2_PACKAGE_FFMPEG_SWSCALE=y
BR2_PACKAGE_FFMPEG_SWRESAMPLE=y
BR2_PACKAGE_FFMPEG_AVFILTER=y
BR2_PACKAGE_FFMPEG_AVCODEC=y
BR2_PACKAGE_FFMPEG_AVFORMAT=y
BR2_PACKAGE_FFMPEG_AVUTIL=y
BR2_PACKAGE_FFMPEG_GPL=y
BR2_PACKAGE_FFMPEG_NONFREE=y

# Video codecs
BR2_PACKAGE_X264=y
BR2_PACKAGE_X265=y
BR2_PACKAGE_LIBVPX=y
BR2_PACKAGE_LIBOPENH264=y
BR2_PACKAGE_LIBTHEORA=y
BR2_PACKAGE_LIBMPEG2=y

# Audio codecs and libraries
BR2_PACKAGE_LIBVORBIS=y
BR2_PACKAGE_LIBOGG=y
BR2_PACKAGE_OPUS=y
BR2_PACKAGE_OPUSFILE=y
BR2_PACKAGE_LIBMAD=y
BR2_PACKAGE_LAME=y
BR2_PACKAGE_SPEEX=y
BR2_PACKAGE_FLAC=y
BR2_PACKAGE_LIBSNDFILE=y
BR2_PACKAGE_LIBSAMPLERATE=y
BR2_PACKAGE_FDK_AAC=y
BR2_PACKAGE_FAAD2=y
BR2_PACKAGE_LIBAO=y
BR2_PACKAGE_OPENCORE_AMR=y
BR2_PACKAGE_VO_AACENC=y
BR2_PACKAGE_TWOLAME=y
BR2_PACKAGE_WAVPACK=y

# Additional video libraries
BR2_PACKAGE_LIBYUV=y
BR2_PACKAGE_LIBASS=y
BR2_PACKAGE_LIBDVDREAD=y
BR2_PACKAGE_LIBDVDNAV=y
BR2_PACKAGE_LIBDVBPSI=y
BR2_PACKAGE_LIBMMS=y
BR2_PACKAGE_RTMPDUMP=y

# Image processing libraries
BR2_PACKAGE_OPENCV3=y

# Audio system
BR2_PACKAGE_ALSA_LIB=y
BR2_PACKAGE_ALSA_LIB_PCM_PLUGINS="all"
BR2_PACKAGE_ALSA_LIB_CTL_PLUGINS="all"
BR2_PACKAGE_ALSA_LIB_ALOAD=y
BR2_PACKAGE_ALSA_LIB_MIXER=y
BR2_PACKAGE_ALSA_LIB_PCM=y
BR2_PACKAGE_ALSA_LIB_RAWMIDI=y
BR2_PACKAGE_ALSA_LIB_HWDEP=y
BR2_PACKAGE_ALSA_LIB_SEQ=y
BR2_PACKAGE_ALSA_LIB_ALISP=y

# Container formats and tools
BR2_PACKAGE_LIBMATROSKA=y
BR2_PACKAGE_LIBEBML=y
BR2_PACKAGE_LIVE555=y

# Additional multimedia utilities
BR2_PACKAGE_GSTREAMER1=y
BR2_PACKAGE_GST1_PLUGINS_BASE=y
BR2_PACKAGE_GST1_PLUGINS_GOOD=y
BR2_PACKAGE_GST1_PLUGINS_BAD=y
BR2_PACKAGE_GST1_PLUGINS_UGLY=y

# SDL for multimedia
BR2_PACKAGE_SDL=y
BR2_PACKAGE_SDL_FBCON=y
BR2_PACKAGE_SDL_IMAGE=y
BR2_PACKAGE_SDL_IMAGE_PNG=y
BR2_PACKAGE_SDL_IMAGE_JPEG=y
BR2_PACKAGE_SDL_MIXER=y
BR2_PACKAGE_SDL_SOUND=y
BR2_PACKAGE_SDL_TTF=y
BR2_PACKAGE_SDL2=y
BR2_PACKAGE_SDL2_KMSDRM=y
BR2_PACKAGE_SDL2_IMAGE=y
BR2_PACKAGE_SDL2_MIXER=y
BR2_PACKAGE_SDL2_TTF=y

# Graphics and image libraries
BR2_PACKAGE_ZLIB=y
BR2_PACKAGE_FREETYPE=y
BR2_PACKAGE_JPEG=y
BR2_PACKAGE_LIBDRM=y
BR2_PACKAGE_LIBPNG=y
BR2_PACKAGE_GIFLIB=y
BR2_PACKAGE_TIFF=y
BR2_PACKAGE_WEBP=y
BR2_PACKAGE_PIXMAN=y

# Development and utility packages
BR2_PACKAGE_EVTEST=y
BR2_PACKAGE_TREE=y
BR2_PACKAGE_LIBPTHREAD_STUBS=y
BR2_PACKAGE_PKGCONF=y
BR2_PACKAGE_GIT=y
BR2_PACKAGE_CMAKE=y
BR2_PACKAGE_MAKE=y
BR2_PACKAGE_LIBTOOL=y

# System configuration
BR2_ENABLE_LOCALE_PURGE=y
BR2_ENABLE_LOCALE_WHITELIST="C en_US"
BR2_TOOLCHAIN_EXTRA_LIBS="libasan"
BR2_OPTIMIZE_S=y
BR2_SSP_NONE=y
BR2_SHARED_LIBS=y
BR2_STRIP_strip=y
EOF
	make oldconfig
	make world
	
	~/install-toolchain.sh
fi
